from .utils import (_emit, 
                    remove_padding, 
                    select_entity_in_inventor_app,
                    get_face_normal,
                    get_face_centroid,
                    get_face_area,
                    filter_face_by_normal_and_centroid,
                    _json_default)
from .geometry import (
    Point2D,
    Point3D,
    PlaneEntity,
    AxisEntity,
    SketchPoint,
    Parameter,
    Curve2d,
    Arc2d,
    LineSegment2d,
    CircleCurve2d,
)
from .reference import (
    get_reference_key_str,
    get_reference_key,
    get_string_reference_key,
    get_entity_by_reference_key,
    get_face_by_transient_key,
    get_edge_by_transient_key,
)
from .metadata import (
    collect_face_metadata,
    collect_edge_metadata,
    is_face_meta_similar,
    is_edge_meta_similar,
)
from .sorting import (
    edge_canonical_key,
    face_canonical_key,
    body_canonical_key,
    stable_sorted_edges,
    stable_sorted_faces,
    stable_sorted_bodies,
    body_stable_rank_in_feature,
)
from .indexing import (
    EntityIndexHelper,
    pick_edge_by_stable_ranks,
    pick_face_by_stable_ranks,
    index_edge,
    index_face,
    get_edge_by_index,
    get_face_by_index,
    get_feature_by_name,
)
from .app import (
    get_inventor_application,
    add_part_document,
    open_inventor_document,
    save__inventor_document,
    get_all_features,
)
from .transient import (
    add_sketch,
    add_sketch_from_last_extrude_end_face,
    transient_point_2d,
    transient_point_3d,
    transient_vector_3d,
    transient_unit_vector_3d,

)
from .features import (
    ExtrudeType,
    ExtrudeDirection,
    add_chamfer_feature,
    add_revolve_feature,
    add_fillet_feature,
    add_extrude_feature,
    convert_to_inventor_curve,
    convert_to_inventor_profile,
    create_extrude_definition,
    convert_extrude_op_to_inventor,
    convert_extrude_dir_to_inventor,
    create_inventor_model_from_sequence,    
    add_sketch2d_line,
    add_sketch2d_circle,
    add_sketch2d_point,
    add_sketch2d_arc,
    add_work_plane,
    add_work_axe,
    add_work_point,
    add_profile,
)
from .enums import (
    enum_name,
    enum_names,
    object_type_name,
    operation_name,
    extent_direction_name,
    extent_type_name,
    map_values_to_names,
)

# Back-compat exported aliases
SketchPlane = PlaneEntity
RevolveAxis = AxisEntity


__all__ = [
    # utils
    "_emit",
    "remove_padding",
    "select_entity_in_inventor_app",
    "_json_default",
    # geometry
    "Point2D",
    "Point3D",
    "PlaneEntity",
    "AxisEntity",
    "SketchPlane",
    "RevolveAxis",
    "SketchPoint",
    "Parameter",
    "Curve2d",
    "Arc2d",
    "LineSegment2d",
    "CircleCurve2d",
    # reference
    "get_reference_key_str",
    "get_reference_key",
    "get_string_reference_key",
    "get_entity_by_reference_key",
    "get_face_by_transient_key",
    "get_edge_by_transient_key",
    # metadata
    "collect_face_metadata",
    "collect_edge_metadata",
    "is_face_meta_similar",
    "is_edge_meta_similar",
    # sorting
    "edge_canonical_key",
    "face_canonical_key",
    "body_canonical_key",
    "stable_sorted_edges",
    "stable_sorted_faces",
    "stable_sorted_bodies",
    "body_stable_rank_in_feature",
    # indexing
    "EntityIndexHelper",
    "pick_edge_by_stable_ranks",
    "pick_face_by_stable_ranks",
    "index_edge",
    "index_face",
    "get_edge_by_index",
    "get_face_by_index",
    "get_feature_by_name",
    # app
    "get_inventor_application",
    "add_part_document",
    "open_inventor_document",
    "save__inventor_document",
    "get_all_features",
    # transient
    "add_sketch",
    "add_sketch_from_last_extrude_end_face",
    "transient_point_2d",
    "transient_point_3d",
    "transient_vector_3d",
    "transient_unit_vector_3d",
    "add_sketch2d_line",
    "add_sketch2d_circle",
    "add_sketch2d_point",
    "add_sketch2d_arc",
    "add_work_plane",
    "add_work_axe",
    "add_work_point",
    "add_profile",
    # features
    "ExtrudeType",
    "ExtrudeDirection",
    "add_chamfer_feature",
    "add_revolve_feature",
    "add_fillet_feature",
    "add_extrude_feature",
    "convert_to_inventor_curve",
    "convert_to_inventor_profile",
    "create_extrude_definition",
    "convert_extrude_op_to_inventor",
    "convert_extrude_dir_to_inventor",
    "create_inventor_model_from_sequence",
    # enums map
    "enum_name",
    "enum_names",
    "object_type_name",
    "operation_name",
    "extent_direction_name",
    "extent_type_name",
    "map_values_to_names",
    # analysis
    "get_face_normal",
    "get_face_centroid",
    "get_face_area",
    "filter_face_by_normal_and_centroid",
]
